### ISSUE TITLE
[Api-test] 프로젝트 조회

### ISSUE THREAD

**Issue by 9sanha** [Scope-Team9/Scope_BackEnd#67]
# 순서

1. 필터를 누를 때

--------
# 테스트

- [x]  회원일 때 추천 결과가 잘 나오는 지
- [x]  무한스크롤
- [x]  기술 스택 필터링
- [x]  북마크 필터링
- [x]  생성일 필터링

**Comment by woodimora** [comment]
조회 api 수정이 필요합니다. 홀딩하겠습니다.
