### ISSUE TITLE
[Api-test] 팀원 평가

### ISSUE THREAD

**Issue by woodimora** [Scope-Team9/Scope_BackEnd#78]
# 순서

1. 팀장이 먼저 팀원을 평가하면, 해당 프로젝트는 완료된 프로젝트로 변경된다.
2. 팀원이 팀원을 평가한다.

--------
# 테스트

- [x] #124
- [x] #125
- [x] 로그인된 사용자는 스스로를 평가 하면 에러를 출력한다.
- [x] 로그인 되어있지 않으면 에러를 출력한다.
- [x] 존재하지 않는 팀원을 평가하면 에러를 출력한다.
- [x] 프로젝트가 존재하지 않으면 에러를 출력한다.
- [x] 로그인된 사용자가 프로젝트의 팀원이 아니면 에러를 출력한다.
- [x] #126
- [x]  자기 자신을 평가했을 때

**Comment by 9sanha** [comment]
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTYzNTg0NDIwNCwiZXhwIjoxNjM1OTMwNjA0fQ.PqLqK4CvEXo2uf13eGJqUR3yYyZofCVyXXGBAuB-8LE

**Comment by 9sanha** [comment]
![image](https://user-images.githubusercontent.com/64877575/139820428-d7efe664-aecb-4399-b439-cc02fdb90ad2.png)
